"""Multimodal QA judgment via GPT-4o (vision + text). Returns dict matching qa_result schema."""
from __future__ import annotations

import base64
import json
import os
from pathlib import Path

from openai import OpenAI

SYSTEM_PROMPT = """You are a strict multimodal QA reviewer for short marketing videos
produced for Korean small-business clients. The videos are generated by an
external AI video platform whose output sometimes has visual and audio defects.
You receive:
- CLIENT INFO (the only source of truth about the brand, services, claims allowed)
- STT TEXT + detected language code
- SCRIPT (optional, intended narration)
- SCENES / GENERATION CONTEXT (optional)
- Sampled FRAMES (representative offsets + scene-boundary frames), in time order

PRIMARY FOCUS — does the video look obviously wrong as a finished product?
A. Visual anomaly QA: floating furniture/objects not resting on the floor,
   broken perspective, distorted wall/ceiling/furniture proportions, composition
   collapse, generation artifacts on object boundaries.
B. Scene relevance QA: objects that have no business appearing in this
   industry/scene context (e.g., a car in a dental clinic shot).
C. Scene duplication QA: same shot repeating, low scene diversity. You will
   be given a separate scene-similarity hint from the pipeline; combine it with
   what you see.
D. Audio language QA: non-Korean voice, or Korean mixed with foreign segments.
E. Then the existing client-information checks (brand mixing, unsupported claims).

Initial bias: prefer to catch obviously broken outputs rather than chase subtle
nits. If a frame would clearly make a viewer say "this is AI-generated and
broken", flag it."""

RULES = """DECISION RULES (apply in order; first match wins on status):
1) Floating furniture/objects clearly not resting on the ground in any frame
   -> detectedFloatingObjects=true, add to visualAnomalyFrames with
   category='floating_furniture', severity high/medium. If high severity in 2+
   frames -> status=retry. If single medium -> status=human_review.
2) Severe spatial distortion (walls/ceiling/objects with broken proportions)
   -> detectedSpatialDistortion=true, add to visualAnomalyFrames with
   category='spatial_distortion'. Severe -> status=human_review.
3) Object clearly unrelated to client_info.industry/scenes appears in frame
   -> detectedIrrelevantObjects=true, add to irrelevantObjectFindings with
   {offsetSec, object, expectedContext, severity}. Clear case -> status=retry.
4) Same shot or near-identical frames repeating across the video
   -> detectedDuplicateScenes=true, add ranges to duplicateSceneRanges with
   {startSec, endSec, similarFrameOffsets, similarity, reason}. If sceneDiversityScore
   < 40 -> status=retry. 40-70 -> warning.
5) Non-Korean voice OR foreign-language segments in STT
   -> detectedForeignLanguageTTS=true (and detectedForeignLanguage=true),
   populate audioLanguageSummary.foreignSegments -> status=retry.
6) Other company / brand name in STT or on-screen
   -> detectedCompanyMixing=true -> status=retry.
7) Claim with specifics (results, %, numbers, awards, certifications, prices,
   exact location) not present in client_info
   -> detectedUnsupportedClaim=true -> status=retry.
8) Industry mismatch — scenes show a different business type vs client_info.industry
   -> detectedWrongIndustry=true -> status=retry.
9) Medical / legal / financial / income exaggeration OR forbiddenClaims hits
   -> status=human_review.
10) Broken subtitles / severely cropped on-screen text
    -> detectedVisualTextIssue=true -> status=human_review.
11) STT vs SCRIPT major divergence
    -> detectedAudioScriptMismatch=true. Risky meaning shift -> human_review,
    otherwise warning.
12) Only minor wording nits -> status=pass.

SCORING: 100=clean, 80-99=pass with warnings, 50-79=retry, <50=fail.
status=fail only when video is unusable (broken file, totally wrong client, no
audio at all, or critical visual breakage across most of the video).

VISUAL/SCENE/AUDIO SUMMARIES (always populate):
- visualQaSummary: one entry per sampled frame
  {offsetSec, observations:[string], spatialOk:bool, floatingObjects:[string], score:0..100}
- sceneQaSummary: one entry per scene segment you can identify
  {sceneIdx, description, expectedThemes:[string], observedThemes:[string],
   matchesIntent:bool, note:string}
- audioLanguageSummary:
  {primary:'ko'|'en'|..., confidence:0..1, detectedSecondary:[lang],
   foreignSegments:[{startSec,endSec,language,text}]}
- sceneDiversityScore: 0..100. 100 = every shot unique.

RETRY PROMPT: when status=retry you MUST write a concrete Korean retryPrompt the
user can paste into the external video-generation platform. Include the correct
client name + industry, services/promotionPoints to feature, forbidden claims to
avoid, AND the specific visual/scene/audio issues to fix this time. <= 600 chars."""

OUTPUT_SCHEMA = """OUTPUT a single JSON object, no markdown, no prose. Schema:
{
  "status": "pass" | "retry" | "human_review" | "fail",
  "score": 0..100,
  "criticalIssues": [string],
  "warnings": [string],

  "detectedForeignLanguage": bool,
  "detectedCompanyMixing": bool,
  "detectedUnsupportedClaim": bool,
  "detectedWrongIndustry": bool,
  "detectedVisualTextIssue": bool,
  "detectedAudioScriptMismatch": bool,

  "detectedFloatingObjects": bool,
  "detectedSpatialDistortion": bool,
  "detectedIrrelevantObjects": bool,
  "detectedDuplicateScenes": bool,
  "detectedForeignLanguageTTS": bool,

  "sceneDiversityScore": number | null,
  "duplicateSceneRanges": [
    {"startSec": number, "endSec": number, "similarFrameOffsets": [number],
     "similarity": number, "reason": string}
  ],
  "visualAnomalyFrames": [
    {"offsetSec": number, "category": "floating_furniture"|"spatial_distortion"|"composition_artifact"|"other",
     "severity": "low"|"medium"|"high", "description": string}
  ],
  "irrelevantObjectFindings": [
    {"offsetSec": number|null, "object": string, "expectedContext": string,
     "severity": "low"|"medium"|"high"}
  ],
  "audioLanguageSummary": {
    "primary": string, "confidence": number,
    "detectedSecondary": [string],
    "foreignSegments": [{"startSec": number, "endSec": number, "language": string, "text": string}]
  },
  "visualQaSummary": [
    {"offsetSec": number, "observations": [string],
     "spatialOk": bool, "floatingObjects": [string], "score": number|null}
  ],
  "sceneQaSummary": [
    {"sceneIdx": number, "description": string, "expectedThemes": [string],
     "observedThemes": [string], "matchesIntent": bool|null, "note": string}
  ],

  "retryPrompt": string,
  "humanReviewReason": string
}"""


def _encode_image(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def _get_client() -> OpenAI:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY not set.")
    return OpenAI(api_key=api_key)


def analyze(
    *,
    client_info: dict,
    stt_text: str,
    stt_language: str,
    frame_paths: list[tuple[Path, float]],
    script: str | None,
    scenes: list | dict | None,
    generation_context: dict | None,
    model: str = "gpt-4o",
) -> dict:
    client = _get_client()

    user_blocks: list[dict] = [
        {"type": "text", "text": "## CLIENT INFO\n" + json.dumps(client_info, ensure_ascii=False, indent=2)},
        {"type": "text", "text": f"## STT (whisper detected language='{stt_language}')\n{stt_text or '(empty)'}"},
    ]
    if script:
        user_blocks.append({"type": "text", "text": "## SCRIPT (intended)\n" + script})
    if scenes is not None:
        user_blocks.append({"type": "text", "text": "## SCENES\n" + json.dumps(scenes, ensure_ascii=False)})
    if generation_context is not None:
        user_blocks.append({"type": "text", "text": "## GENERATION CONTEXT\n" + json.dumps(generation_context, ensure_ascii=False)})

    user_blocks.append({"type": "text", "text": f"## FRAMES ({len(frame_paths)} samples, in time order)"})
    for path, offset in frame_paths:
        user_blocks.append({"type": "text", "text": f"frame @ {offset:.2f}s"})
        user_blocks.append({
            "type": "image_url",
            "image_url": {
                "url": f"data:image/jpeg;base64,{_encode_image(path)}",
                "detail": "low",
            },
        })

    user_blocks.append({"type": "text", "text": RULES})
    user_blocks.append({"type": "text", "text": OUTPUT_SCHEMA})

    resp = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_blocks},
        ],
        response_format={"type": "json_object"},
        temperature=0.1,
    )
    raw = resp.choices[0].message.content or "{}"
    return json.loads(raw)
